apiVersion: v2
name: nemo-smart
description: Smart Shinan villege by Nemo Corps.
icon: https://www.whereurl.com/favicon.ico

type: application
version: 0.1.0

appVersion: "1.16.0"
maintainers:
  - name: ParkSC
    email: ma5@imnemo.com
  - name: kaonmir
    email: sonjeff@naver.com
