apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.name}}
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
        - name: smart
          image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
          #   imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{.Values.service.port}}
