apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{.Values.name}}-vs
  namespace: default
spec:
  gateways:
    - default/gateway-app
  hosts: {{- toYaml .Values.hosts | nindent 2}}
  http:
    - route:
        - destination:
            host: "{{.Values.name}}.{{.Values.namespace}}.svc.cluster.local"
            port:
              number: 80
